# Auto Label Git Action Config
# 'label_name'
#   - path_of_diff/where/code_lives/to_base_label_upon

# Any change to any file in .github/workflows
'GitHub Actions':
  - '.github/workflows/*'
  
# Any changes to file or subfolders in /frontend
'Frontend':
  - 'ipad/**/*'

# Any change to any file in any directory with a .env in name
'Environment Variables':
  - '**/*.env*'